name: CI

on:
  push:
    branches:
      - main
      - release-*
  pull_request: {}
  merge_group:
    types: [checks_requested]
  workflow_dispatch:
    inputs:
      save-output:
        type: boolean
        required: false
        description: 'Save _output directory to GitHub'
        default: false

env:
  # Common versions
  GO_VERSION: '1.24.2'
  GOLANGCI_VERSION: 'v2.2.0'
  DOCKER_BUILDX_VERSION: 'v0.10.0'
  XPKG_ACCESS_ID: ${{ secrets.XPKG_ACCESS_ID }}

jobs:
  detect-noop:
    runs-on: ubuntu-24.04
    outputs:
      noop: ${{ steps.noop.outputs.should_skip }}
    steps:
      - name: Detect No-op Changes
        id: noop
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5
        with:
          paths_ignore: '["**.md", "**.png", "**.jpg"]'
          do_not_skip: '["workflow_dispatch", "schedule", "push"]'
          concurrent_skipping: false


  lint:
    runs-on: ubuntu-24.04
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: ${{ env.GO_VERSION }}

      # We could run 'make lint' to ensure our desired Go version, but we prefer
      # this action because it leaves 'annotations' (i.e. it comments on PRs to
      # point out linter violations).
      - name: Lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8
        with:
          version: ${{ env.GOLANGCI_VERSION }}

  check-diff:
    runs-on: ubuntu-24.04
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check Diff
        run: make check-diff

  unit-tests:
    runs-on: ubuntu-24.04
    needs:
      - detect-noop
    if: needs.detect-noop.outputs.noop != 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true

      - name: Fetch History
        run: git fetch --prune --unshallow

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run Unit Tests
        run: make test

  publish-image:
    runs-on: ubuntu-latest
    needs:
      - detect-noop
      - unit-tests
      - lint
    if: ${{ github.actor != 'dependabot[bot]' && needs.detect-noop.outputs.noop != 'true' }}
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
        with:
          platforms: all

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3
        with:
          version: ${{ env.DOCKER_BUILDX_VERSION }}
          install: true

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true

      - name: Fetch History
        run: git fetch --prune --unshallow

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Publish Artifacts to GitHub
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        # Inputs are accessible across workflow_dispatch and workflow_call.
        # https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context
        if: ${{ inputs.save-output }}
        with:
          name: output
          path: _output/**

      - name: Login to Upbound Marketplace
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: xpkg.upbound.io/upbound
          username: ${{ secrets.XPKG_ACCESS_ID }}
          password: ${{ secrets.XPKG_ACCESS_TOKEN }}

      - name: Publish Artifacts
        run: |
          make publish BRANCH_NAME=${GITHUB_REF##*/}
        env:
          XPKG_ACCESS_ID: ${{ secrets.XPKG_ACCESS_ID }}
          XPKG_TOKEN: ${{ secrets.XPKG_TOKEN }}

  publish-addon:
    runs-on: ubuntu-latest
    needs:
      - detect-noop
      - unit-tests
      - lint
      - publish-image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install up
        uses: upbound/action-up@v1
        with:
          skip-login: true
          channel: main
          version: v0.39.0-384.g0a0c8634

      - name: Login to Upbound Marketplace
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: xpkg.upbound.io/upbound
          username: ${{ secrets.XPKG_ACCESS_ID }}
          password: ${{ secrets.XPKG_ACCESS_TOKEN }}

      - name: Build chart
        run: |
          make helm.build

      - name: Create working directory
        run: |
          mkdir -p tmp-addon-xpkg
          cd tmp-addon-xpkg

      - name: Build and Publish
        working-directory: tmp-addon-xpkg
        if: env.XPKG_ACCESS_ID != ''
        run: |
          CHART_VERSION=$(make --no-print-directory -C ../ helm.version)
          cp ../crossplane.yaml .

          # Build resources
          mkdir helm
          mv ../_output/charts/marketplace-mcp-server-${CHART_VERSION}.tgz helm/chart.tgz

          # Build artifact
          up xpkg build

          # Find artifact
          XPKG_FILENAME=$(find . -name "*.xpkg" -type f -printf "%f\n")
          echo $XPKG_FILENAME

          # Publish artifact
          export ADDON_NAME=addon-$(printf '%s' "$GITHUB_REPOSITORY" | sed 's/.*\///')
          echo $ADDON_NAME

          up xpkg push xpkg.upbound.io/upbound/$ADDON_NAME:$CHART_VERSION -f $XPKG_FILENAME